title: Adeep Hande # your name (or website title) here
logo: "/images/Adeep.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  B.Tech, Computer Science and Engineering at IIIT Tiruchirappalli(2022)
  <br>
  Research Intern at National University of Ireland, Galway
  <br>
  Mentor: Dr.Bharathi Raja Asoka Chakravarthi
  <br><br>
  <a href="https://www.linkedin.com/in/adeep-hande-74922216b/">LinkedIn</a> 
theme: jekyll-theme-minimal
