title: Adeep Hande # your name (or website title) here
logo: "/images/Adeep.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  B.Tech CSE at Indian Institute of Information Technology ,Tiruchirappalli ,India
  Deep learning Enthusiast and Natural Language processing in code-mixed dataset.
  <br>
  Currently working as a Research Intern under Dr.Bharatiraja Asoka Chakravarthi in
  National University of Ireland, Galway.Working in multi-task learning among 
  under-resourced languages for tasks like sentiment analysis and offensive language 
  detection.
  <br><br>
  <a href="https://www.linkedin.com/in/adeep-hande-74922216b/">View My LinkedIn Profile</a> 
  <br> 
  <a href="https://adeepH/">View My Github Repositories</a>
  
  
  
  
  
  
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
