title: Adeep Hande # your name (or website title) here
logo: "/images/Adeep.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Junior Computer Science undergrad at IIIT Trichy,India.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/adeep-hande-74922216b/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://adeepH/">View My Github Repositories</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
